name: Prompt Runner

on:
  push:
    branches:
      - master

jobs:
  run-prompt:
    if: contains(github.event.head_commit.message, 'prompt:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extrair prompt do commit
        id: get-prompt
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          PROMPT=$(echo "$COMMIT_MSG" | sed -n 's/.*prompt:\(.*\)/\1/p')
          echo "prompt=$PROMPT" >> $GITHUB_OUTPUT

      - name: Preparar contexto (primeira vez pega tudo)
        id: get-context
        run: |
          if [ ! -f .context_initialized.flag ]; then
            CONTEXT=$(find . -type f \
              -not -path "./.git/*" \
              -not -path "./node_modules/*" \
              \( -name "*.js" -o -name "*.ts" -o -name "*.json" -o -name "*.html" -o -name "*.css" \) \
              -exec sh -c 'echo "==== $1 ===="; cat "$1"' _ {} \; | head -c 100000)
            touch .context_initialized.flag
            git add .context_initialized.flag
            git commit -m "Initialize context snapshot" || echo "Flag já existe"
            git push
          else
            FILES=$(git diff --name-only HEAD~1 HEAD)
            CONTEXT=""
            for F in $FILES; do
              if [[ -f "$F" ]]; then
                CONTEXT+="==== $F ====\n"
                CONTEXT+=$(cat "$F")
                CONTEXT+="\n"
              fi
            done
            CONTEXT=$(echo "$CONTEXT" | head -c 100000)
          fi
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

      - name: Rodar ChatGPT (OpenAI API)
        id: ai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          JSON_PAYLOAD=$(jq -n \
            --arg context "${{ steps.get-context.outputs.context }}" \
            --arg prompt "${{ steps.get-prompt.outputs.prompt }}" \
            '{
              model: "gpt-4o-mini",
              response_format: {type: "json_object"},
              messages: [
                {role: "system", content: "Você é um assistente que edita código. Responda SOMENTE c
