name: Prompt Runner

on:
  push:
    branches:
      - master

jobs:
  run-prompt:
    if: contains(github.event.head_commit.message, 'prompt:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Preparar contexto do código
        id: get-context
        run: |
          # Coleta apenas arquivos de código relevantes
          CONTEXT=$(find . -type f \
            -not -path "./.git/*" \
            -not -path "./node_modules/*" \
            \( -name "*.js" -o -name "*.ts" -o -name "*.json" -o -name "*.html" -o -name "*.css" \) \
            -exec sh -c 'echo "==== $1 ===="; cat "$1"' _ {} \;)

          # Limita tamanho do contexto (20k chars)
          CONTEXT=$(echo "$CONTEXT" | head -c 20000)

          echo "context<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTEXT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Extrair prompt do commit
        id: get-prompt
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          PROMPT=$(echo "$COMMIT_MSG" | sed -n 's/.*prompt:\(.*\)/\1/p')
          echo "prompt=$PROMPT" >> $GITHUB_OUTPUT

      - name: Rodar ChatGPT (OpenAI API)
        id: ai
        run: |
          # Escapa contexto e prompt para JSON seguro
          CONTEXT_JSON=$(echo "${{_
