Run if [ ! -f .context_initialized.flag ]; then
  if [ ! -f .context_initialized.flag ]; then
    find . -type f \
      -not -path "./.git/*" \
      -not -path "./node_modules/*" \
      \( -name "*.js" -o -name "*.ts" -o -name "*.json" -o -name "*.html" -o -name "*.css" \) \
      -exec sh -c 'echo "==== $1 ===="; cat "$1"' _ {} \; > full_context.txt
    touch .context_initialized.flag
    git add .context_initialized.flag
    git commit -m "Initialize context snapshot" || echo "Flag já existe"
    git push
  else
    FILES=$(git diff --name-only HEAD~1 HEAD)
    CONTEXT=""
    for F in $FILES; do
      if [[ -f "$F" ]]; then
        CONTEXT+="==== $F ====\n"
        CONTEXT+=$(cat "$F")
        CONTEXT+="\n"
      fi
    done
    echo -e "$CONTEXT" > full_context.txt
  fi
  echo "context<<EOF" >> $GITHUB_OUTPUT
  cat full_context.txt >> $GITHUB_OUTPUT
  echo "EOF" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: Process completed with exit code 128.
0s
0s
0s
0s
